version: '3'

services:
    app:
        build:
            context: ./app/
            dockerfile: Dockerfile
        expose:
            - 3000
        ports:
            - 3000:3000
        restart: on-failure
        volumes:
            - ./app/:/app

    # here could be the other applications
